name: GitHub Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Run spec-prod
        uses: w3c/spec-prod@v2

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download spec-prod-result artifact
        uses: actions/download-artifact@v4
        with:
          name: spec-prod-result
          path: _site
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
